h = eye(4);
color = [1 0 0];

origin = h(1:3,4);
origin_3x = [origin, origin, origin,];

clf
hold on;
axis([-4 4 -4 4 -4 4]);
grid on;
view(3);
axis equal;

handle = quiver3(origin_3x(1,:), ...
        origin_3x(1,:), ...
        origin_3x(2,:), ...
        h(1, 1:3)     , ...
        h(2, 1:3)     , ...
        h(3, 1:3)     , ...
        'maxheadsize', .5 ,...
        'linewidth',    1 ,...
        'color', color, ...
        'marker',  '.', ...
        'markersize', 20 ...
        );
